language: node_js
node_js:
  - node
  - 7.0.0
services: mongodb
before_script:
  - mongo test_lucid --eval 'db.createUser({user:"adonis",pwd:"adonis",roles:["dbOwner"]});'
sudo: false
install:
  - npm install --no-optional
script:
  - DB=mongodb database=test_lucid user=adonis password=adonis npm test
notifications:
